apiVersion: v1
kind: Service
metadata:
  labels:
    name: tensorflow-worker
    role: service
  name: tensorflow-wk-service
spec:
  ports:
    - port: 23333
      targetPort: 23333
  selector:
    name: tensorflow-worker
